version: '3'
services:
   clang-env:
      build: tools/clang
      image: shri314/clang
      entrypoint: sleep 10
      restart: "no"
      user: ${CURRENT_UID}
      volumes:
         - .:/src
   clang-libcpp-env:
      build: tools/clang-libcpp
      image: shri314/clang-libcpp
      entrypoint: sleep 10
      restart: "no"
      user: ${CURRENT_UID}
      volumes:
         - .:/src
      depends_on:
         - clang-env
   clang-libcpp-boost-env:
      build: tools/clang-libcpp-boost
      image: shri314/clang-libcpp-boost
      entrypoint: sleep infinity
      container_name: clang-libcpp-boost-env
      restart: always
      user: ${CURRENT_UID}
      volumes:
         - .:/src
      depends_on:
         - clang-libcpp-env
