version: 2

############################################################################

references:

############################################################################

jobs:
   build-images:
      docker:
         - image: docker:git
      steps:
         - checkout
         - setup_remote_docker:
            version: 17.11.0-ce
         - run:
            name: Login
            command: |
               if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "develop" ]
               then
                  echo "Docker User: $DOCKER_USER"
                  echo 'Y' | docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
               fi
         - run:
            name: Creating images
            command: |
               apk update
               apk add --no-cache py-pip make
               pip install docker-compose
               make build sample-run down
         - deploy:
            name: Pushing images
            command: |
               if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "develop" ]
               then
                  make push
               fi

############################################################################

workflows:
   version: 2

   main:
      jobs:
         - build-images:
            filters:
               branches:
                  only:
                     - master
                     - develop
